/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as RevisionsRouteImport } from './routes/revisions'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as ProblemsRouteImport } from './routes/problems'
import { Route as OauthSuccessRouteImport } from './routes/oauth-success'
import { Route as LoginRouteImport } from './routes/login'
import { Route as InterviewsRouteImport } from './routes/interviews'
import { Route as InterviewHistoryRouteImport } from './routes/interview-history'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ContestsRouteImport } from './routes/contests'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorkspaceSessionIdRouteImport } from './routes/workspace.$sessionId'
import { Route as InterviewHistorySessionIdRouteImport } from './routes/interview-history/$sessionId'
import { Route as InterviewSessionIdReportRouteImport } from './routes/interview.$sessionId.report'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const RevisionsRoute = RevisionsRouteImport.update({
  id: '/revisions',
  path: '/revisions',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ProblemsRoute = ProblemsRouteImport.update({
  id: '/problems',
  path: '/problems',
  getParentRoute: () => rootRouteImport,
} as any)
const OauthSuccessRoute = OauthSuccessRouteImport.update({
  id: '/oauth-success',
  path: '/oauth-success',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const InterviewsRoute = InterviewsRouteImport.update({
  id: '/interviews',
  path: '/interviews',
  getParentRoute: () => rootRouteImport,
} as any)
const InterviewHistoryRoute = InterviewHistoryRouteImport.update({
  id: '/interview-history',
  path: '/interview-history',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ContestsRoute = ContestsRouteImport.update({
  id: '/contests',
  path: '/contests',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceSessionIdRoute = WorkspaceSessionIdRouteImport.update({
  id: '/workspace/$sessionId',
  path: '/workspace/$sessionId',
  getParentRoute: () => rootRouteImport,
} as any)
const InterviewHistorySessionIdRoute =
  InterviewHistorySessionIdRouteImport.update({
    id: '/$sessionId',
    path: '/$sessionId',
    getParentRoute: () => InterviewHistoryRoute,
  } as any)
const InterviewSessionIdReportRoute =
  InterviewSessionIdReportRouteImport.update({
    id: '/interview/$sessionId/report',
    path: '/interview/$sessionId/report',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contests': typeof ContestsRoute
  '/dashboard': typeof DashboardRoute
  '/interview-history': typeof InterviewHistoryRouteWithChildren
  '/interviews': typeof InterviewsRoute
  '/login': typeof LoginRoute
  '/oauth-success': typeof OauthSuccessRoute
  '/problems': typeof ProblemsRoute
  '/profile': typeof ProfileRoute
  '/revisions': typeof RevisionsRoute
  '/signup': typeof SignupRoute
  '/interview-history/$sessionId': typeof InterviewHistorySessionIdRoute
  '/workspace/$sessionId': typeof WorkspaceSessionIdRoute
  '/interview/$sessionId/report': typeof InterviewSessionIdReportRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contests': typeof ContestsRoute
  '/dashboard': typeof DashboardRoute
  '/interview-history': typeof InterviewHistoryRouteWithChildren
  '/interviews': typeof InterviewsRoute
  '/login': typeof LoginRoute
  '/oauth-success': typeof OauthSuccessRoute
  '/problems': typeof ProblemsRoute
  '/profile': typeof ProfileRoute
  '/revisions': typeof RevisionsRoute
  '/signup': typeof SignupRoute
  '/interview-history/$sessionId': typeof InterviewHistorySessionIdRoute
  '/workspace/$sessionId': typeof WorkspaceSessionIdRoute
  '/interview/$sessionId/report': typeof InterviewSessionIdReportRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contests': typeof ContestsRoute
  '/dashboard': typeof DashboardRoute
  '/interview-history': typeof InterviewHistoryRouteWithChildren
  '/interviews': typeof InterviewsRoute
  '/login': typeof LoginRoute
  '/oauth-success': typeof OauthSuccessRoute
  '/problems': typeof ProblemsRoute
  '/profile': typeof ProfileRoute
  '/revisions': typeof RevisionsRoute
  '/signup': typeof SignupRoute
  '/interview-history/$sessionId': typeof InterviewHistorySessionIdRoute
  '/workspace/$sessionId': typeof WorkspaceSessionIdRoute
  '/interview/$sessionId/report': typeof InterviewSessionIdReportRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contests'
    | '/dashboard'
    | '/interview-history'
    | '/interviews'
    | '/login'
    | '/oauth-success'
    | '/problems'
    | '/profile'
    | '/revisions'
    | '/signup'
    | '/interview-history/$sessionId'
    | '/workspace/$sessionId'
    | '/interview/$sessionId/report'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contests'
    | '/dashboard'
    | '/interview-history'
    | '/interviews'
    | '/login'
    | '/oauth-success'
    | '/problems'
    | '/profile'
    | '/revisions'
    | '/signup'
    | '/interview-history/$sessionId'
    | '/workspace/$sessionId'
    | '/interview/$sessionId/report'
  id:
    | '__root__'
    | '/'
    | '/contests'
    | '/dashboard'
    | '/interview-history'
    | '/interviews'
    | '/login'
    | '/oauth-success'
    | '/problems'
    | '/profile'
    | '/revisions'
    | '/signup'
    | '/interview-history/$sessionId'
    | '/workspace/$sessionId'
    | '/interview/$sessionId/report'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContestsRoute: typeof ContestsRoute
  DashboardRoute: typeof DashboardRoute
  InterviewHistoryRoute: typeof InterviewHistoryRouteWithChildren
  InterviewsRoute: typeof InterviewsRoute
  LoginRoute: typeof LoginRoute
  OauthSuccessRoute: typeof OauthSuccessRoute
  ProblemsRoute: typeof ProblemsRoute
  ProfileRoute: typeof ProfileRoute
  RevisionsRoute: typeof RevisionsRoute
  SignupRoute: typeof SignupRoute
  WorkspaceSessionIdRoute: typeof WorkspaceSessionIdRoute
  InterviewSessionIdReportRoute: typeof InterviewSessionIdReportRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/revisions': {
      id: '/revisions'
      path: '/revisions'
      fullPath: '/revisions'
      preLoaderRoute: typeof RevisionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/problems': {
      id: '/problems'
      path: '/problems'
      fullPath: '/problems'
      preLoaderRoute: typeof ProblemsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oauth-success': {
      id: '/oauth-success'
      path: '/oauth-success'
      fullPath: '/oauth-success'
      preLoaderRoute: typeof OauthSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/interviews': {
      id: '/interviews'
      path: '/interviews'
      fullPath: '/interviews'
      preLoaderRoute: typeof InterviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/interview-history': {
      id: '/interview-history'
      path: '/interview-history'
      fullPath: '/interview-history'
      preLoaderRoute: typeof InterviewHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contests': {
      id: '/contests'
      path: '/contests'
      fullPath: '/contests'
      preLoaderRoute: typeof ContestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workspace/$sessionId': {
      id: '/workspace/$sessionId'
      path: '/workspace/$sessionId'
      fullPath: '/workspace/$sessionId'
      preLoaderRoute: typeof WorkspaceSessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/interview-history/$sessionId': {
      id: '/interview-history/$sessionId'
      path: '/$sessionId'
      fullPath: '/interview-history/$sessionId'
      preLoaderRoute: typeof InterviewHistorySessionIdRouteImport
      parentRoute: typeof InterviewHistoryRoute
    }
    '/interview/$sessionId/report': {
      id: '/interview/$sessionId/report'
      path: '/interview/$sessionId/report'
      fullPath: '/interview/$sessionId/report'
      preLoaderRoute: typeof InterviewSessionIdReportRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface InterviewHistoryRouteChildren {
  InterviewHistorySessionIdRoute: typeof InterviewHistorySessionIdRoute
}

const InterviewHistoryRouteChildren: InterviewHistoryRouteChildren = {
  InterviewHistorySessionIdRoute: InterviewHistorySessionIdRoute,
}

const InterviewHistoryRouteWithChildren =
  InterviewHistoryRoute._addFileChildren(InterviewHistoryRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContestsRoute: ContestsRoute,
  DashboardRoute: DashboardRoute,
  InterviewHistoryRoute: InterviewHistoryRouteWithChildren,
  InterviewsRoute: InterviewsRoute,
  LoginRoute: LoginRoute,
  OauthSuccessRoute: OauthSuccessRoute,
  ProblemsRoute: ProblemsRoute,
  ProfileRoute: ProfileRoute,
  RevisionsRoute: RevisionsRoute,
  SignupRoute: SignupRoute,
  WorkspaceSessionIdRoute: WorkspaceSessionIdRoute,
  InterviewSessionIdReportRoute: InterviewSessionIdReportRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
